
# Use different management port as security rule
management:
    port: 8081
    security.enabled: false

# Enable shutdown
endpoints.shutdown.enabled: true

# Thrift server config
sbmvtAbcThriftServer:
  port: 3000
  name: sbmvt-abc-thrift-server

# Eureka Config
eureka:
  instance:
    appname: ${sbmvtAbcThriftServer.name}
    nonSecurePort: ${sbmvtAbcThriftServer.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client.serviceUrl.defaultZone: http://localhost:8761/eureka/

# DB Config
sbmvtAbc.datasource:
  # For more see http://tomcat.apache.org/tomcat-7.0-doc/jdbc-pool.html#Common_Attributes
  username: sbmvt
  password: hehehe 
  testOnBorrow: true
  validationQuery: SELECT 1
  url: jdbc:mysql://sbmvt-mysql-test:3306/sbmvt-abc

# RabbitMQ Config
rabbitmq:
  host: sbmvt-rabbitmq-test
  port: 5672
  username: sbmvt
  password: hehehe
  vhost: sbmvt

# Redis Config
sbmvtAbc.redis:
  database: 0
  host: sbmvt-redis-test
  port: 6379
  password: hehehe
  timeout: 2000
  pool:
    max-active: 16
    max-wait: -1
    min-idle: 2
    max-idle: 8

# LocalCache
sbmvtAbc.localCache:
  ttlSecs: 10
  capacity: 2

# RemoteCache
sbmvtAbc.memcachedCache:
  #serverList: 192.168.99.100:11211, 192.168.99.101:11211
  serverList: 192.168.99.100:11211
  ttlSecs: 10

# Profiles
spring:
  profiles.active: test
---
spring:
  profiles: test

logging:
  level.ROOT: INFO
---
spring:
  profiles: online

logging:
  level.ROOT: INFO
  pattern.console:
  file: my-sample-server.log

# Eureka Config Online
eureka:
  client.serviceUrl.defaultZone: http://eureka-server-online:8761/eureka/

# DB Config Online
sbmvtAbc.datasource.url: jdbc:mysql://sbmvt-mysql-online:3306/sbmvt-abc

# RabbitMQ Config Online
rabbitmq.host: sbmvt-rabbitmq-online

# Redis Config Online
spring.redis.host: sbmvt-redis-online